version: '2'

services:
  nginx:
    container_name: nginx
    image: nginx:1.19.5
    restart: always
    ports:
      - 8088:8088
    volumes:
      - ./log/nginx:/var/log/nginx
      - ./configs/nginx/default.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - app

  app:
    container_name: app
    build: ./docker_images/php
    restart: always
    expose:
      - 9000
    volumes:
      - ./src:/var/www/html:cached
      - ./configs/php/php.ini:/usr/local/etc/php/php.ini      

  mariadb:
    container_name: db
    image: mariadb:10.5.8
    restart: always
    ports:
      - 3306:3306
    volumes:
      - "./configs/mysql/mysql:/etc/mysql/conf.d"
      - db_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456

  elasticsearch:
    container_name: elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    image: elasticsearch:7.9.3
    restart: always
    ports:
      - 9200:9200
    volumes:
      - ./configs/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
  
  logstash:
    container_name: logstash
    image: logstash:7.9.3
    restart: always
    volumes:
      - ./configs/logstash/logstash.conf:/usr/share/logstash/config/logstash.conf
      - ./log/nginx:/log/nginx
    command: bin/logstash -f /usr/share/logstash/config/logstash.conf
  
  kibana:
    container_name: kibana
    image: kibana:7.9.3
    restart: always
    ports:
      - 5601:5601

  redis:
    container_name: redis
    image: redis:6.0.9
    command: redis-server --requirepass 123456
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./configs/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - redis_volume:/var/lib/redis
    environment:
     - REDIS_REPLICATION_MODE=master

  mailcatcher:
    container_name: mailcatcher
    image: schickling/mailcatcher
    restart: always
    ports:
      - 1080:1080

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8.9-management
    restart: always
    ports:
      - 15672:15672

  varnish:
    container_name: varnish
    build: ./docker_images/varnish
    restart: always
    ports:
      - 80:80
    volumes:
      - ./configs/varnish/default.vcl:/etc/varnish/default.vcl
      - ./log/varnish/varnish.log:/var/log/varnish/varnish.log

volumes:
  db_volume:
  redis_volume: